title: Ethan McIntosh
logo: /docs/assets/img/headshot_small.png
description: 
  Geospatial Data Analyst
  
    <br>
    Applied Transportation Researcher

    <br>
    <a href="https://www.linkedin.com/in/ethan-m-274378215">View My LinkedIn Profile</a> 



#show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jemoji
markdown: GFM