title: Ethan McIntosh
logo: /assets/img/headshot_small.png
description: 
  Geospatial Data Analyst
  
    <br>
    Applied Researcher
    
    <br>
       <a href="https://github.com/mciethan">View My GitHub Profile</a>
    <br>
  <a href="https://www.linkedin.com/in/ethan-m-274378215">View My LinkedIn Profile</a> 



#show_downloads: false
theme: jekyll-theme-minimal
